name: test
on:
  issue_comment:
    types:
      - created

jobs:
  wow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: do
        run: echo ${{ github.event.issue }}
