name: test
on:
  issue_comment:
    types:
      - created

jobs:
  wow:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: do thing
        run: node ci-add.js
